spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import: jwt.yml
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/Banggabgo?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379
    timeout: 3

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: { kakao client-id }
            client-secret: { kakao client-secretKey }
            scope: profile_nickname, account_email, profile_image
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
          google:
            client-id: { google client-id }
            client-secret: { google client-secret }
            scope: profile, email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server:
  port: 8080