spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import: jwt.yml
  datasource:
    username: root
    password: root
    url: ${MYSQL_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  redis:
    host: ${REDIS_CONTAINER}
    port: 6379
    timeout: 3

server:
  port: 8083