version: "3.2"

services:
  nginx:
    build:
      context: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
  mysql:
    build:
      context: mysql
    ports:
      - "3306:3306"
    env_file:
      - env/mysql.env

  redis:
    build:
      context: redis
    ports:
      - "6379:6379"

  api1:
    restart: always
    build:
      context: api
    env_file:
      - env/api.env
    environment:
      - RABBIT_MQ_CONTAINER=rabbitmq
      - USE_PROFILE=prod
      - API_PORT=8083
      - REDIS_CONTAINER=redis
      - MONGO_CONTAINER=mongo
      - MYSQL_CONTAINER=mysql
      - API_DDL_OPTION=update
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - redis
      - mongo
  api2:
    restart: always
    build:
      context: api
    env_file:
      - env/api.env
    environment:
      - RABBIT_MQ_CONTAINER=rabbitmq
      - USE_PROFILE=prod
      - API_PORT=8084
      - REDIS_CONTAINER=redis
      - MONGO_CONTAINER=mongo
      - MYSQL_CONTAINER=mysql
      - API_DDL_OPTION=update
    ports:
      - "8084:8084"
    depends_on:
      - mysql
      - redis
      - mongo
  rabbitmq:
    build:
      context: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
      - "61614:61614"

  mongo:
    env_file:
      - env/mongo.env
    build:
      context: mongo
    restart: always
    ports:
      - "27017:27017"
networks:
  bangapgo:
    driver: bridge
