version: '3.2'

services:
  banggabda-mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD : root
    networks:
      - bangapgo
  banggabda-redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - bangapgo

  api:
    image: wlals4253/banggabgo
    ports:
      - "8083:8083"
    networks:
      - bangapgo
networks:
  bangapgo:
    driver: bridge